version: "3"
services:

  rise-arm:
    build:
      context: .
      dockerfile: Dockerfile.arm
    depends_on:
      - redis
      - postgres
    ports:
      - "127.0.0.1:5555:5555"
    networks:
      - overlay
    environment:
      NETWORK: mainnet
    restart: on-failure

  redis:
    image: arm32v6/redis:5-alpine
    networks:
      - overlay
    restart: on-failure

  postgres:
    image: arm32v6/postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rise
      POSTGRES_DB: rise_db
    networks:
      - overlay
    restart: on-failure

networks:
  overlay:
