FROM arm32v6/postgres:11-alpine

COPY ./qemu-arm-static /usr/bin/qemu-arm-static

RUN wget https://downloads.rise.vision/snapshots/mainnet/latest -O latestsnap.sql.gz && \
    mkdir -p /docker-entrypoint-initdb.d && \
    mv latestsnap.sql.gz /docker-entrypoint-initdb.d

RUN rm /usr/bin/qemu-arm-static
