FROM postgres:11-alpine

RUN wget https://downloads.rise.vision/snapshots/mainnet/latest -O latestsnap.sql.gz && \
    mkdir -p /docker-entrypoint-initdb.d && \
    mv latestsnap.sql.gz /docker-entrypoint-initdb.d
