version: '3'
services:
  # ----- NODE 1
  rise_1:
    build:
      context: ../../
      dockerfile: ./docker/devnet/Dockerfile
    depends_on:
      - postgres_1
    ports:
      # rise node - p2p
      - '5501:9999'
      # rise node - api
      - '5502:9998'
      # node inspector
      - '9201:9229'
    networks:
      overlay:
        ipv4_address: 172.16.238.101
    environment:
      NETWORK: devnet
#      NODE_ENV: test
    volumes:
      # config
      - ./node_config.1.json:/home/rise/config.json
      # root
      - ../../node_modules:/home/rise/rise-node/node_modules
      - ../../package.json:/home/rise/rise-node/package.json
      - ../../tsconfig.base.json:/home/rise/rise-node/tsconfig.base.json
      - ../../lerna.json:/home/rise/rise-node/lerna.json
      - ../../yarn.lock:/home/rise/rise-node/yarn.lock
      - ../../packages:/home/rise/rise-node/packages
    restart: on-failure
#    stdin_open: true
#    tty: true

  postgres_1:
    build:
      context: ../../
      dockerfile: ./docker/files/Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rise
      POSTGRES_DB: rise_db
    ports:
      - '5432:5432'
    networks:
      - overlay
    restart: on-failure

  # ----- NODE 2
  rise_2:
    build:
      context: ../../
      dockerfile: ./docker/devnet/Dockerfile
    depends_on:
      - postgres_2
    ports:
      # rise node - p2p
      - '5511:9999'
      # rise node - api
      - '5512:9998'
      # node inspector
      - '9211:9229'
    networks:
      overlay:
        ipv4_address: 172.16.238.102
    environment:
      NETWORK: devnet
#      NODE_ENV: test
    volumes:
      # config
      - ./node_config.2.json:/home/rise/config.json
      # root
      - ../../node_modules:/home/rise/rise-node/node_modules
      - ../../package.json:/home/rise/rise-node/package.json
      - ../../lerna.json:/home/rise/rise-node/lerna.json
      - ../../yarn.lock:/home/rise/rise-node/yarn.lock
      - ../../packages:/home/rise/rise-node/packages
    restart: on-failure

  postgres_2:
    build:
      context: ../../
      dockerfile: ./docker/files/Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: rise
      POSTGRES_DB: rise_db
    networks:
      - overlay
    restart: on-failure

networks:
  overlay:
    ipam:
      config:
        - subnet: 172.16.238.0/24
