export const Symbols = {
  generic: {
    appConfig: Symbol.for('appConfig'),
    constants: Symbol.for('constants'),
    crypto: Symbol.for('crypto'),
    genesisBlock: Symbol.for('genesisBlock'),
    hookSystem: Symbol.for('hookSystem'),
    socketIO: Symbol.for('socketIO'),
    zschema: Symbol.for('zschema'),
    nonce: Symbol.for('nonce'),
  },
  helpers: {
    db: Symbol.for('dbHelper'),
    jobsQueue: Symbol.for('jobsQueue'),
    logger: Symbol.for('logger'),
    sequence: Symbol.for('sequence'),
    timeToEpoch: Symbol.for('timeToEpoch'),
  },
  logic: {
    account: Symbol.for('account'),
    appState: Symbol.for('appState'),
    block: Symbol.for('block'),
    blockReward: Symbol.for('blockReward'),
    broadcaster: Symbol.for('broadcaster'),
    peer: Symbol.for('peer'),
    peers: Symbol.for('peer'),
    transaction: Symbol.for('transaction'),
    txpool: Symbol.for('txPool'),
  },
  models: {
    accounts: Symbol.for('accountsModel'),
    blocks: Symbol.for('blocksModel'),
    forkStats: Symbol.for('forkStats'),
    info: Symbol.for('infoModel'),
    migrations: Symbol.for('migrations'),
    peers: Symbol.for('peers'),
    transactions: Symbol.for('transactions'),
  },
  modules: {
    accounts: Symbol.for('accountsModule'),
    blocks: Symbol.for('blocksModule'),
    blocksSubmodules: {
      chain: Symbol.for('chainSub'),
      process: Symbol.for('processSub'),
      utils: Symbol.for('utilsSub'),
      verify: Symbol.for('verifySub'),
    },
    fork: Symbol.for('forkModule'),
    peers: Symbol.for('peers'),
    system: Symbol.for('systemModule'),
    transactions: Symbol.for('transactionsModule'),
    transport: Symbol.for('transportModule'),
  },
  names: {
    helpers: {
      balancesSequence: Symbol.for('balancesSequence'),
      dbSequence: Symbol.for('dbSequence'),
      defaultSequence: Symbol.for('defaultSequence'),
    },
  },
};
